name: CI-Build

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  # workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive

    steps:
      - name: Get code from repo
        uses: actions/checkout@v3

      - name: Build LaTeX pdf-output
        run: |
          pdflatex main.tex
          biber main
          pdflatex main.tex
          pdflatex main.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main_build.pdf
